version: '3'
services:
  db:
    image: mysql:8.4
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '@Hung0112256'
      MYSQL_DATABASE: smarthome_db
      MYSQL_HOST: ''
    volumes:
      - mysqld:/var/lib/mysql

  web:
    build: ./be_rtos
    command: python -u manage.py runserver 0.0.0.0:8000
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./be_rtos:/be_rtos
    links:
      - db:mydb

volumes:
  mysqld:
