# Generated by Django 5.0.6 on 2024-06-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='uid',
            new_name='id',
        ),
    ]
