# Generated by Django 5.0.6 on 2024-06-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_uid_device_id_rename_uid_devicetype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
