# Generated by Django 5.0.6 on 2024-06-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_device_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
