# Generated by Django 5.0.6 on 2024-07-05 04:27

import shortuuidfield.fields
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_device_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
