# Generated by Django 5.0.6 on 2024-07-05 04:38

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
